//
//  MicdStyleKit.m
//  ProjectName
//
//  Created by AuthorName on 3/30/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "MicdStyleKit.h"


@implementation MicdStyleKit

#pragma mark Cache

static UIImage* _imageOfProgressBar = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawProgressBar
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.161 green: 0.745 blue: 0.867 alpha: 1];

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(375, 0)];
    [bezierPath addLineToPoint: CGPointMake(375, 20)];
    [bezierPath addLineToPoint: CGPointMake(360, 20)];
    [bezierPath addCurveToPoint: CGPointMake(360, 19.24) controlPoint1: CGPointMake(360, 20) controlPoint2: CGPointMake(360, 19.72)];
    [bezierPath addCurveToPoint: CGPointMake(375, 10) controlPoint1: CGPointMake(368.48, 18.59) controlPoint2: CGPointMake(375, 14.7)];
    [bezierPath addCurveToPoint: CGPointMake(360, 0.76) controlPoint1: CGPointMake(375, 5.3) controlPoint2: CGPointMake(368.48, 1.41)];
    [bezierPath addCurveToPoint: CGPointMake(360, 0) controlPoint1: CGPointMake(360, 0.28) controlPoint2: CGPointMake(360, 0)];
    [bezierPath addLineToPoint: CGPointMake(375, 0)];
    [bezierPath closePath];
    [UIColor.blackColor setFill];
    [bezierPath fill];


    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(13, 0)];
    [bezier2Path addCurveToPoint: CGPointMake(13, 0.76) controlPoint1: CGPointMake(13, 0) controlPoint2: CGPointMake(13, 0.28)];
    [bezier2Path addCurveToPoint: CGPointMake(0, 10) controlPoint1: CGPointMake(5.65, 1.41) controlPoint2: CGPointMake(0, 5.3)];
    [bezier2Path addCurveToPoint: CGPointMake(13, 19.24) controlPoint1: CGPointMake(-0, 14.7) controlPoint2: CGPointMake(5.65, 18.59)];
    [bezier2Path addCurveToPoint: CGPointMake(13, 20) controlPoint1: CGPointMake(13, 19.72) controlPoint2: CGPointMake(13, 20)];
    [bezier2Path addLineToPoint: CGPointMake(0, 20)];
    [bezier2Path addLineToPoint: CGPointMake(0, 0)];
    [bezier2Path addLineToPoint: CGPointMake(13, 0)];
    [bezier2Path addLineToPoint: CGPointMake(13, 0)];
    [bezier2Path closePath];
    [UIColor.blackColor setFill];
    [bezier2Path fill];


    //// border Drawing
    UIBezierPath* borderPath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(1, 1, 373, 18) cornerRadius: 9];
    [color setStroke];
    borderPath.lineWidth = 2;
    [borderPath stroke];
}

#pragma mark Generated Images

+ (UIImage*)imageOfProgressBar
{
    if (_imageOfProgressBar)
        return _imageOfProgressBar;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(375, 20), NO, 0.0f);
    [MicdStyleKit drawProgressBar];

    _imageOfProgressBar = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfProgressBar;
}

#pragma mark Customization Infrastructure

- (void)setProgressBarTargets: (NSArray*)progressBarTargets
{
    _progressBarTargets = progressBarTargets;

    for (id target in self.progressBarTargets)
        [target setImage: MicdStyleKit.imageOfProgressBar];
}


@end
