//
//  MicdStyleKit.h
//  ProjectName
//
//  Created by AuthorName on 3/30/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface MicdStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* progressBarTargets;

// Drawing Methods
+ (void)drawProgressBar;

// Generated Images
+ (UIImage*)imageOfProgressBar;

@end
