//
//  MicdStyleKit.m
//  ProjectName
//
//  Created by AuthorName on 4/4/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "MicdStyleKit.h"


@implementation MicdStyleKit

#pragma mark Cache

static UIImage* _imageOfProgressBar = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawProgressBar
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.161 green: 0.745 blue: 0.867 alpha: 1];

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(375, 0)];
    [bezierPath addLineToPoint: CGPointMake(375, 15)];
    [bezierPath addLineToPoint: CGPointMake(365, 15)];
    [bezierPath addCurveToPoint: CGPointMake(365, 14.43) controlPoint1: CGPointMake(365, 15) controlPoint2: CGPointMake(365, 14.79)];
    [bezierPath addCurveToPoint: CGPointMake(375, 7.5) controlPoint1: CGPointMake(370.65, 13.94) controlPoint2: CGPointMake(375, 11.03)];
    [bezierPath addCurveToPoint: CGPointMake(365, 0.57) controlPoint1: CGPointMake(375, 3.97) controlPoint2: CGPointMake(370.65, 1.06)];
    [bezierPath addCurveToPoint: CGPointMake(365, 0) controlPoint1: CGPointMake(365, 0.21) controlPoint2: CGPointMake(365, 0)];
    [bezierPath addLineToPoint: CGPointMake(375, 0)];
    [bezierPath closePath];
    [UIColor.blackColor setFill];
    [bezierPath fill];


    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(10, 0)];
    [bezier2Path addCurveToPoint: CGPointMake(10, 0.57) controlPoint1: CGPointMake(10, 0) controlPoint2: CGPointMake(10, 0.21)];
    [bezier2Path addCurveToPoint: CGPointMake(0, 7.5) controlPoint1: CGPointMake(4.35, 1.06) controlPoint2: CGPointMake(0, 3.97)];
    [bezier2Path addCurveToPoint: CGPointMake(10, 14.43) controlPoint1: CGPointMake(-0, 11.03) controlPoint2: CGPointMake(4.35, 13.94)];
    [bezier2Path addCurveToPoint: CGPointMake(10, 15) controlPoint1: CGPointMake(10, 14.79) controlPoint2: CGPointMake(10, 15)];
    [bezier2Path addLineToPoint: CGPointMake(0, 15)];
    [bezier2Path addLineToPoint: CGPointMake(0, 0)];
    [bezier2Path addLineToPoint: CGPointMake(10, 0)];
    [bezier2Path addLineToPoint: CGPointMake(10, 0)];
    [bezier2Path closePath];
    [UIColor.blackColor setFill];
    [bezier2Path fill];


    //// border Drawing
    UIBezierPath* borderPath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(1, 1, 373, 13) cornerRadius: 6.5];
    [color setStroke];
    borderPath.lineWidth = 2;
    [borderPath stroke];
}

#pragma mark Generated Images

+ (UIImage*)imageOfProgressBar
{
    if (_imageOfProgressBar)
        return _imageOfProgressBar;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(375, 15), NO, 0.0f);
    [MicdStyleKit drawProgressBar];

    _imageOfProgressBar = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfProgressBar;
}

#pragma mark Customization Infrastructure

- (void)setProgressBarTargets: (NSArray*)progressBarTargets
{
    _progressBarTargets = progressBarTargets;

    for (id target in self.progressBarTargets)
        [target setImage: MicdStyleKit.imageOfProgressBar];
}


@end
