//
//  MicdStyleKit.h
//  ProjectName
//
//  Created by AuthorName on 3/28/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface MicdStyleKit : NSObject

// Drawing Methods
+ (void)drawProgressBarWithFrame: (CGRect)frame progressWidth: (CGFloat)progressWidth;

// Generated Images
+ (UIImage*)imageOfProgressBarWithFrame: (CGRect)frame progressWidth: (CGFloat)progressWidth;

@end
