//
//  WireTapStyleKit.h
//  wiretap
//
//  Created by Timmietch on 2/16/15.
//  Copyright (c) 2015 cleverKnot. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface WireTapStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* homeViewTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* micdBackgroundTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* singleRecordingCellTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* recordButtonTargets;

// Drawing Methods
+ (void)drawHomeView;
+ (void)drawMicdBackground;
+ (void)drawSingleRecordingCell;
+ (void)drawRecordButton;
+ (void)drawGearsWithPositiveGearRotation: (CGFloat)positiveGearRotation negativeGearRotation: (CGFloat)negativeGearRotation;
+ (void)drawBackgroundCordWithColor: (UIColor*)color;
+ (void)drawGripCircle;

// Generated Images
+ (UIImage*)imageOfHomeView;
+ (UIImage*)imageOfMicdBackground;
+ (UIImage*)imageOfSingleRecordingCell;
+ (UIImage*)imageOfRecordButton;
+ (UIImage*)imageOfGearsWithPositiveGearRotation: (CGFloat)positiveGearRotation negativeGearRotation: (CGFloat)negativeGearRotation;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
