//
//  WireTapStyleKit.h
//  wiretap
//
//  Created by Timmietch on 4/10/15.
//  Copyright (c) 2015 cleverKnot. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface WireTapStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* homeViewTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* gearsCircleTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* splashScreenTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* pauseCircleButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* playCircleButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* playButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* pauseButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* thumbImageTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* reverseDoubleArrowTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* shareButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* editCircleTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* progressBarNoBorderTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* micdBackgroundTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* recordButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* recordButtonHighlightedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iconBlackTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* recordButtonForSplashScreenTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* recordButtonRotatorTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* loveMicdTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* anyCommentsTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* pencilTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* pauseAssetTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* progressTimeIndicatorViewTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* clearButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tableviewFaderTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* micdAppIconTargets;

// Drawing Methods
+ (void)drawHomeView;
+ (void)drawGearsCircle;
+ (void)drawTestCanvas;
+ (void)drawSplashScreen;
+ (void)drawPauseCircleButton;
+ (void)drawPlayCircleButton;
+ (void)drawPlayButton;
+ (void)drawPauseButton;
+ (void)drawRewindButtonWithAmountBack: (NSString*)amountBack;
+ (void)drawForwardButtonWithAmountForward: (NSString*)amountForward;
+ (void)drawThumbImage;
+ (void)drawForwardDoubleArrowWithAmountForward: (NSString*)amountForward;
+ (void)drawReverseDoubleArrow;
+ (void)drawShareButton;
+ (void)drawEditCircle;
+ (void)drawTextfieldBackerWithFrame: (CGRect)frame number: (CGFloat)number;
+ (void)drawProgressBarWithColor7: (UIColor*)color7;
+ (void)drawProgressBarNoBorder;
+ (void)drawMicdBackground;
+ (void)drawRecordButton1WithArcEndAngle: (CGFloat)arcEndAngle arcStartAngle: (CGFloat)arcStartAngle;
+ (void)drawIconRed;
+ (void)drawRecordButton;
+ (void)drawCanvas1WithArcEndAngle: (CGFloat)arcEndAngle arcStartAngle: (CGFloat)arcStartAngle;
+ (void)drawRecordButtonHighlighted;
+ (void)drawMic;
+ (void)drawMicRed;
+ (void)drawIconBlack;
+ (void)drawRecordButtonForSplashScreen;
+ (void)drawCanvas2;
+ (void)drawRecordButtonRotator;
+ (void)drawGearsWithPositiveGearRotation: (CGFloat)positiveGearRotation negativeGearRotation: (CGFloat)negativeGearRotation;
+ (void)drawSettingsViewWithColor7: (UIColor*)color7;
+ (void)drawMicdLogoWithColor7: (UIColor*)color7;
+ (void)drawLoveMicd;
+ (void)drawAnyComments;
+ (void)drawBackgroundCordWithColor: (UIColor*)color;
+ (void)drawPencil;
+ (void)drawPauseAsset;
+ (void)drawProgressTimeIndicatorView;
+ (void)drawClearButton;
+ (void)drawPlayAssetWithArcStart: (CGFloat)arcStart arcEnd: (CGFloat)arcEnd;
+ (void)drawTableviewFader;
+ (void)drawMicdAppIcon;

// Generated Images
+ (UIImage*)imageOfHomeView;
+ (UIImage*)imageOfGearsCircle;
+ (UIImage*)imageOfSplashScreen;
+ (UIImage*)imageOfPauseCircleButton;
+ (UIImage*)imageOfPlayCircleButton;
+ (UIImage*)imageOfPlayButton;
+ (UIImage*)imageOfPauseButton;
+ (UIImage*)imageOfRewindButtonWithAmountBack: (NSString*)amountBack;
+ (UIImage*)imageOfForwardButtonWithAmountForward: (NSString*)amountForward;
+ (UIImage*)imageOfThumbImage;
+ (UIImage*)imageOfForwardDoubleArrowWithAmountForward: (NSString*)amountForward;
+ (UIImage*)imageOfReverseDoubleArrow;
+ (UIImage*)imageOfShareButton;
+ (UIImage*)imageOfEditCircle;
+ (UIImage*)imageOfTextfieldBackerWithFrame: (CGRect)frame number: (CGFloat)number;
+ (UIImage*)imageOfProgressBarWithColor7: (UIColor*)color7;
+ (UIImage*)imageOfProgressBarNoBorder;
+ (UIImage*)imageOfMicdBackground;
+ (UIImage*)imageOfRecordButton1WithArcEndAngle: (CGFloat)arcEndAngle arcStartAngle: (CGFloat)arcStartAngle;
+ (UIImage*)imageOfRecordButton;
+ (UIImage*)imageOfRecordButtonHighlighted;
+ (UIImage*)imageOfIconBlack;
+ (UIImage*)imageOfRecordButtonForSplashScreen;
+ (UIImage*)imageOfRecordButtonRotator;
+ (UIImage*)imageOfGearsWithPositiveGearRotation: (CGFloat)positiveGearRotation negativeGearRotation: (CGFloat)negativeGearRotation;
+ (UIImage*)imageOfSettingsViewWithColor7: (UIColor*)color7;
+ (UIImage*)imageOfLoveMicd;
+ (UIImage*)imageOfAnyComments;
+ (UIImage*)imageOfPencil;
+ (UIImage*)imageOfPauseAsset;
+ (UIImage*)imageOfProgressTimeIndicatorView;
+ (UIImage*)imageOfClearButton;
+ (UIImage*)imageOfPlayAssetWithArcStart: (CGFloat)arcStart arcEnd: (CGFloat)arcEnd;
+ (UIImage*)imageOfTableviewFader;
+ (UIImage*)imageOfMicdAppIcon;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
